source 'https://rubygems.org'

ruby '2.4.1'

gem 'capybara'
gem 'nokogiri'
gem 'pry'
gem 'rspec'
gem 'rubocop'
gem 'sinatra'
gem 'thin'
#gem 'webdrivers'
gem 'selenium-webdriver'
gem 'chromedriver-helper'
gem 'geckodriver-helper'
gem 'firefox'
gem 'haml'
gem 'yarn'
